### ISSUE TITLE
Bitcode bundle could not be generated

### ISSUE THREAD

**Issue by reizer22** [Connatix/ConnatixPlayerSDK-cocoapod#3]
Hello! When I try to archive the application, I get an error:

> bitcode bundle could not be generated because '/Pods/ConnatixPlayerSDK/ConnatixPlayerSDK.framework/ConnatixPlayerSDK' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build file '/Pods/ConnatixPlayerSDK/ConnatixPlayerSDK.framework/ConnatixPlayerSDK' for architecture arm64

Internet solutions did not solve the problem. I use the 1.2.1 version of the SDK.
Maybe you know a solution to create an application archive with your SDK?

**Comment by mihaifischerConnatix** [comment]
Hi, I think we found the issue - it seems Xcode doesn't use bitcode if you don't Archive your project even if you use the Enable bitcode flag. 

We managed to overcome in our new 1.2.4 version. 

Please update your pod and let us know if there are any other issues.
